# Generated by Django 4.2.4 on 2023-08-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(upload_to='blog_videos/'),
        ),
    ]
