# Generated by Django 4.2.4 on 2023-08-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_post_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_file',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blog_videos/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.post')),
            ],
        ),
    ]
