# Generated by Django 4.2.4 on 2023-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_post_video_file_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(default=2, upload_to='blog_videos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
