# Generated by Django 4.2.4 on 2023-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_post_video_file_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=False, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
