# Generated by Django 4.2.4 on 2023-08-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_usersaves_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersaves',
            name='imgpk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.bookpage'),
        ),
    ]
