# Generated by Django 4.2.4 on 2023-08-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_usersaves_imgpk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSaves',
        ),
    ]
