# Generated by Django 4.2.4 on 2023-08-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_page_image_paths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_pages',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='recipes.bookpage'),
        ),
    ]
