# Generated by Django 4.2.4 on 2023-10-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_bookpage_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='keywords',
            field=models.CharField(max_length=5000),
        ),
    ]
