# Generated by Django 4.2.4 on 2023-10-28 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0018_alter_bookpage_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='keywords',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.CreateModel(
            name='User_meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
