# Generated by Django 4.2.4 on 2023-10-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_bookpage_keywords_user_meta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_meta',
        ),
    ]
