# Generated by Django 4.2.4 on 2023-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verfied',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_books',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
