# Generated by Django 4.2.4 on 2023-10-29 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_userbook_remove_userprofile_user_books_userbookpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookpage',
            name='user',
        ),
    ]
