# Generated by Django 4.2.4 on 2023-10-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_remove_userbookpage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='pages',
            field=models.ManyToManyField(through='recipes.UserBookPage', to='recipes.bookpage'),
        ),
        migrations.AddField(
            model_name='userbookpage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
