# Generated by Django 4.2.4 on 2023-11-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_alter_userprofile_user_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultUserProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='default_profile_pics/')),
            ],
        ),
    ]
